spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/memo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: sym
    password: qwer1234@

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        #JPA? ??? SQL? ??? ???? ??
    generate-ddl: true
    #true? ?? ??? ????? ???? ??? ??? ????? ????.

